In [1]:
from centerlineLib import *

In [2]:
testCenterline = centerlineComputor()
centerlineCor = testCenterline.getCenterline(".\\New_820_Lava_Cor_pre_mask\*.png", 1, True)

Done!
---------------
There are 562443 points in total. Now sampleling 7000 points from them
---------------
Done!
---------------
Begin creating a MST of the sampled points cloud
---------------
Begin calculating nearby points for each point
---------------
Nearby points calculation Done! Total: 7000 points, 168000 edges.
---------------
Begin construct graph
---------------
Graph construction Done!
---------------
Begin calculate MST
---------------
MST calculation Done!
---------------
MST creation Done!


  0% (3 of 7000) |                       | Elapsed Time: 0:00:00 ETA:   0:05:14

Start centerline iteration: 0


  9% (636 of 7000) |#                    | Elapsed Time: 0:00:14 ETA:   0:02:22

Overflow!


 37% (2635 of 7000) |#######             | Elapsed Time: 0:00:59 ETA:   0:01:26

Overflow!


100% (7000 of 7000) |####################| Elapsed Time: 0:02:38 Time:  0:02:38


156.91432976722717 156.9042751789093 0.2539355754852295 4.797264575958252
---------------
There are 7000 points in total. Now sampleling 7000 points from them
---------------
Done!
---------------
Begin creating a MST of the sampled points cloud
---------------
Begin calculating nearby points for each point
---------------
Nearby points calculation Done! Total: 7000 points, 133000 edges.
---------------
Begin construct graph
---------------
Graph construction Done!
---------------
Begin calculate MST
---------------
MST calculation Done!
---------------
MST creation Done!


C:\Users\Zifeng Li\Anaconda3\envs\Helmsley3DMIP\lib\site-packages\networkx\drawing\nx_pylab.py:579: MatplotlibDeprecationWarning: 
The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
  if not cb.iterable(width):


[4481]
MST has 7000 nodes. Now begin to trim the graph.
Done! Trimed 6480 nodes. Now MST has 520 nodes left.
Now begin reconstruct endpoints
Done! Now MST has 890 nodes left.


[array([164,  89,  18], dtype=int64),
 array([164,  90,  19], dtype=int64),
 array([165,  90,  20], dtype=int64),
 array([166,  90,  19], dtype=int64),
 array([167,  92,  19], dtype=int64),
 array([169,  92,  19], dtype=int64),
 array([170,  94,  20], dtype=int64),
 array([170,  94,  19], dtype=int64),
 array([173,  93,  18], dtype=int64),
 array([173,  95,  18], dtype=int64),
 array([175,  96,  18], dtype=int64),
 array([175,  96,  18], dtype=int64),
 array([176,  94,  17], dtype=int64),
 array([177,  94,  17], dtype=int64),
 array([178,  94,  17], dtype=int64),
 array([178,  94,  18], dtype=int64),
 array([178,  95,  18], dtype=int64),
 array([180,  95,  17], dtype=int64),
 array([181,  95,  17], dtype=int64),
 array([181,  94,  17], dtype=int64),
 array([179,  93,  16], dtype=int64),
 array([179,  92,  16], dtype=int64),
 array([180,  92,  16], dtype=int64),
 array([180,  91,  15], dtype=int64),
 array([181,  89,  15], dtype=int64),
 array([179,  89,  15], dtype=int64),
 array([179,