In [1]:
import numpy as np
import pptk
import networkx as nx
import imageio
import glob
import re
from random import sample, seed
from scipy.spatial import distance
from time import strftime
import os
import scipy.optimize as optimize
import math
from sklearn.linear_model import LinearRegression
import time
import copy
from moving_least_square import *
from tempfile import TemporaryFile
from collections import defaultdict
from vpython import *
from math import *
scene = canvas()

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [2]:
seed(20)
if os.name == 'nt': # Windows
    system_win = 1
else:
    system_win = 0

In [3]:
# Given the data points, return the MST of the point cloud generated from the PNG files and an array 
# of points positions
# Param: data: an array of points coordinate. Each point's coordinate should has the format of [x, y, z]
#        drawMST: boolean value. Default is false. If set true, the function will also draw a MST graph at the end
#        sampleNumber: int value. Default is 5000. This function will only sample <sampleNumber> points from the data
# Return: a NetworkX graph representing the Minimum spanning tree of the data points
def getMSTFromDataPoint(data, drawMST: bool=False, sampleNumber: int=5000):
    # Read points data from PNGs 
    if(sampleNumber > len(data)):
        sampleNumber = len(data)
        
    # default sample 5000 points from the whole set, otherwise it would take too long
    print("---------------")
    print("There are " + str(len(data)) + " points in total. Now sampleling " + str(sampleNumber) + " points from them")
    sample_data = np.asarray(sample(list(data), sampleNumber))
    print("---------------")
    print("Done!")
    
    #display the points 
    #displayPoints(sample_data, 1.3)
    
    #Create a networkX graph instance that represent MST
    print("---------------")
    print("Begin creating a MST of the sampled points cloud")
    MST = CreateMSTGraph(sample_data)
    print("---------------")
    print("MST creation Done!")
    
    if(drawMST):
        nx.draw(MST, dict(enumerate(sample_data[:, :2])))
        
    return (MST, sample_data)
    

In [4]:
# This function will invoke a pptk viewer to render the points 
# Param: data: an array of points coordinate. Each point's coordinate should has the format of [x, y, z]
#       pointSize: the size of the point to be rendered on the screen
# Return: none

def displayPoints(data, pointSize):
    v = pptk.viewer(data)
    v.set(point_size=pointSize)

In [5]:
# This function will read a txt file and convert its content to point data, which is an array of points coordinate. 
# Each point's coordinate should has the format of [x, y, z]
# Param: filePath: the file path of the txt file
# Return: an array of points coordinate. Each point's coordinate has the format of [x, y, z]
def readPointFromTXT(filePath):
    data = np.genfromtxt(fname=filePath, skip_header=0)
    return data

In [6]:
# This function will read a series of PNG file and convert its content to point data, which is an array of points coordinate. 
# Each point's coordinate will have the format of [x, y, z]
# Param: filePath: the file path of the PNG files. Each file should be named as 1.png, 2.png, 3.png ... etc. All the png file should 
# be ordered by the their topological order from their original dicom file
# Return: an array of points coordinate. Each point's coordinate has the format of [x, y, z]
def ReadPointFromPNG(filepath):
    print("---------------")
    print("Begin reading points data from PNG files")
    path_list = [im_path for im_path in glob.glob(filepath)]
    
    if system_win:
        path_list_parsed = [re.split('\\\\|\.', path) for path in path_list]
    else:
        path_list_parsed = [re.split('/|\.', path) for path in path_list]
    path_list_parsed_valid = [x for x in path_list_parsed if x[-1] == 'png']
    path_list_parsed_valid = sorted(path_list_parsed_valid, key=lambda x:int(x[-2]))
    
    print("There are", len(path_list_parsed_valid),"PNG files, now convert them to point coordinates in 3D")
    imageData = []
    delta = 0.5
    totalThickness = len(path_list_parsed_valid) * 3 * delta
    for path in path_list_parsed_valid:
        s = ""
        if system_win:
            s = "\\"
        else:
            s = "/"
        s = s.join(path)
        s = s[:-4] + '.png'
        image = imageio.imread(s)
        imageData.append(image)
    
    zxy = np.transpose(np.where(imageData))
    xyz = zxy[:, [1, 2, 0]]
    xyz[:, 2] = totalThickness - xyz[:, 2]*3*delta
    print("Done!")
    return xyz

In [7]:
# This function is used to limited the number of edges in the original graph.
# Instead of creating a graph with full connectivity, this function will return 
# a list of neighbor points for each point and we will only connect them in the graph
def getNearbyPoints(pointsData):
    D = distance.squareform(distance.pdist(pointsData))
    closestIndicies = np.argsort(D, axis=1)
    closestDis = np.sort(D, 1)
    threshold = 10 # This number can be changed. The greater this number, the more edges
    return (closestIndicies[:, 1:threshold], closestDis[:, 1:threshold])

In [8]:
def CreateMSTGraph(pointsData):
    print("---------------")
    print("Begin calculating nearby points for each point")
    nearbyInfo = getNearbyPoints(pointsData)
    print("---------------")
    print("Nearby points calculation Done!")
    print("---------------")
    print("Begin construct graph")
    G=nx.Graph()
    closestIndicies = nearbyInfo[0]
    closestDis = nearbyInfo[1]
    for firstPIndex in range(len(closestIndicies)):
        for second in range(len(closestIndicies[firstPIndex])):
            secondPIndex = closestIndicies[firstPIndex][second]
            G.add_edge(firstPIndex, secondPIndex , weight = closestDis[firstPIndex][second])
    print("---------------")
    print("Graph construction Done!")
    print("---------------")
    print("Begin calculate MST")
    G = nx.minimum_spanning_tree(G)
    print("---------------")
    print("MST calculation Done!")
    return G

In [9]:
# Impliment the collect algorithm for 3D points in the paper
def collectPoints1(P: int, PStar: int):
    global H_glo
    global graph
    global pointsCor3D
    global A

    A.append(P)
    for edge in graph.edges(P):
        Pj = edge[1]
        if(Pj) not in A and distance.euclidean(pointsCor3D[Pj], pointsCor3D[PStar]) < H_glo:
            collectPoints1(Pj, PStar)

In [10]:
# This function will collect the neighbors of PStar and return a list of this points's index
# Param: PStar: the index of the point that we want to find its neighbors
# This function will also maintain the dictionary of the distance between points and the weight 
# between points. 
def collectPointsNonrec(PStar: int, H:int):
    
    global graph
    global pointsCor3D
    global distance_dict 
    global dirty_dict
    
    toExplore = [PStar]
    A = [PStar]
    distance_dict[(PStar, PStar)] = 0
    weight_dict[((PStar, PStar))] = 1
    
    while len(toExplore) > 0:
        curP = toExplore[0]
        del toExplore[0]
        for Pj in graph.neighbors(curP):
            if(Pj) not in A:
                
                # Maintain the dictionary of distance and weight between points
                if (Pj, PStar) not in distance_dict or (PStar, Pj) not in distance_dict or \
                dirty_dict[PStar] == 1 or dirty_dict[Pj] == 1:
                    dist_temp = distance.euclidean(pointsCor3D[Pj], pointsCor3D[PStar])
                    distance_dict[(Pj, PStar)] = dist_temp
                    distance_dict[(PStar, Pj)] = dist_temp
                    weight_dict[((PStar, Pj))] = weightFun(PStar, Pj)
                    weight_dict[((Pj, PStar))] = weightFun(PStar, Pj)
                    dirty_dict[Pj] = 0
                    dirty_dict[PStar] = 0
                    
                if distance_dict[(Pj, PStar)] < H:
                    toExplore.append(Pj)
                    A.append(Pj)
    return A

In [11]:
def weightFun(P1, P2):
    global distance_dict 
    global dirty_dict
    global pointsCor3D
    if(P1 == P2):
        return 1
    return math.exp(-1 * (distance_dict[(P1, P2)]**2)/(H_glo**2))

In [12]:
def calculateRegressionPlane(PStar, A: list):
    global pointsCor3D
    global H_glo
    global weight_dict
    global curPlaneGuess
    #global curScalar
    #global curALen
    '''
    weightKeyList = [(PStar, x) for x in A[curALen:]]
    wM = np.array([weight_dict[k] for k in weightKeyList])
    
    xMatrix = np.array([pointsCor3D[point][0] for point in A[curALen:]])
    yMatrix = np.array([pointsCor3D[point][1] for point in A[curALen:]])
    zMatrix = np.array([pointsCor3D[point][2] for point in A[curALen:]])
    scalarList = np.array([np.sum(xMatrix**2*wM), 2*np.sum(xMatrix*yMatrix*wM), 2*np.sum(xMatrix*wM), \
                           -2*np.sum(xMatrix*zMatrix*wM), np.sum(yMatrix**2*wM), 2*np.sum(yMatrix*wM), \
                           -2*np.sum(yMatrix*zMatrix*wM), np.sum(wM) ,-2*np.sum(zMatrix*wM), \
                           np.sum(zMatrix**2*wM)]) + curScalar
    '''
    
    weightKeyList = [(PStar, x) for x in A]
    wM = np.array([weight_dict[k] for k in weightKeyList])
    
    xMatrix = np.array([pointsCor3D[point][0] for point in A])
    yMatrix = np.array([pointsCor3D[point][1] for point in A])
    zMatrix = np.array([pointsCor3D[point][2] for point in A])
    
    def f(params):
        a, b, c = params 
        loss = sum(((a * xMatrix + b*yMatrix + c - zMatrix)**2)*wM)
        #loss = a**2*scalarList[0] +  a*b*scalarList[1] + a*c*scalarList[2] + a*scalarList[3] + b**2*scalarList[4]\
        #+ b*c*scalarList[5] + b*scalarList[6] + c**2*scalarList[7] + c*scalarList[8] + scalarList[9]
        
        '''
        for point in A:
            point_cor = pointsCor3D[point]
            loss += ((a*point_cor[0] + b*point_cor[1] + c - point_cor[2])**2)*weight_dict[((point, PStar))]
            #loss += ((a*point_cor[0] + b*point_cor[1] + c - point_cor[2])**2)*weightFun(PStar, point)
        '''
        return loss
    
    result = optimize.minimize(f, curPlaneGuess, method = 'Nelder-Mead')
    
    if result.success:
        fitted_params = result.x
    else:
        raise ValueError(result.message)
        
    curPlaneGuess = fitted_params
    #curScalar = scalarList
    #curALen = len(A)
    
    return fitted_params

In [13]:
def projectPoints(params, A: list):
    global pointsCor3D
    a, b, c = params
    normal = np.asarray([a, b, -1])
    normal = normal / np.linalg.norm(normal)
    pointOnPlane = np.asarray([0, 0, c])
    projectionPointsCor = []
    for point in A:
        point_cor = np.asarray(pointsCor3D[point])
        pointToPlaneV = point_cor - pointOnPlane
        dist = np.dot(normal, pointToPlaneV)
        projectionPointcor = point_cor - dist*normal
        projectionPointsCor.append(list(projectionPointcor))
    return projectionPointsCor

In [14]:
# this function converted the 3D coordinate system of points in a plane to 2D, returns a list of new coordinates
# each of them also has x, y and z component but z is equal to 0
# this finction also will return the info of the plane, which can be used to convert a 2D coordinate to 3D again
# The format of the plane info is [u, v, origin] (u is a unit vector in 3D representing plane's x axis, y is a unit 
# vector in 3D representing plane's y axis, origin is a coordinate in 3D of plane's origin )
def convertTo2DCor(pointsCor, planeParam):
    a, b, c = planeParam
    origin = np.array([0, 0, c])
    u = np.array([0, 0, c]) - np.array([1, 1, a + b + c])
    u = u / np.linalg.norm(u)
    normal = np.array([a, b, -1])
    v = np.cross(u, normal)
    v = v / np.linalg.norm(v)
    convertedPointsCor = []
    
    for pointCor in pointsCor:
        oriV = np.array(pointCor) - origin
        new_x = np.dot(oriV, u)
        new_y = np.dot(oriV, v)
        convertedPointsCor.append([new_x, new_y, 0])
        
    planeInfo = [u, v, origin]
    
    return (convertedPointsCor, planeInfo)
    

In [15]:
# Param: targetPoint: the index of the point that we want to find its neighbors and their coordinate in 2D 
# Return: the 2D coordinate of the 3D points and the information of the regression plane, which the points are located
# require gloable perameters graph and pointsCor3D

def get2DCorFrom3D(targetPoint):
    
    global graph
    global pointsCor3D
    global H_glo
    global H_delta
    global min_neighbors
    
    localPoints = []

    while (len(localPoints) < min_neighbors):
        localPoints = collectPointsNonrec(targetPoint, H_glo)
        H_glo += H_delta

    params = calculateRegressionPlane(targetPoint, localPoints)

    projectionPointsCor = projectPoints(params, localPoints)

    points2DCor, planeInfo = convertTo2DCor(projectionPointsCor, params)

    return (points2DCor, planeInfo)

In [16]:
# This function takes a single point's 2D coordinate and transform it into 3D base on the planeInfo
def get3DCorFrom2D(pointCor, planeInfo):
    u, v, origin = planeInfo
    vectorElem1 = pointCor[0]*u
    vectorElem2 = pointCor[1]*v
    newCor = vectorElem1 + vectorElem2 + origin
    
    return newCor

In [17]:
#compue the line regression
def calculateRegressionLine(pointsCor):
    X = np.array([x[0] for x in pointsCor]).reshape(-1, 1)
    Y = np.array([x[1] for x in pointsCor]).reshape(-1, 1)
    linear_regressor = LinearRegression()  # create object for the class
    linear_regressor.fit(X, Y)  # perform linear regression
    
    return(linear_regressor.coef_[0], linear_regressor.intercept_[0])

In [18]:
def rotatePointsCor(pointsCor, lineCoef):
    pointsCor = np.array(pointsCor)
    theta = math.atan(lineCoef)
    c, s = math.cos(theta), math.sin(theta)
    R = np.array([(c,-s, 1), (s, c, 1)])
    newPointsCor = []
    
    for point in pointsCor:
        newPointsCor.append(R.dot(point))
    return np.asarray(newPointsCor)

In [19]:
def deleteChild(child:int):
    global removedNodeDict
    global graph_centerline
    global pointsCor3D_centerline
    
    graph_centerline.remove_node(child)
    
    for grandChild in removedNodeDict[child]:
        if(graph_centerline.has_node(grandChild)):
            deleteChild(grandChild)
        

In [20]:
def addBackChildren(parent:int, curDepth:int):
    global removedNodeDict
    global graph_centerline
    global pointsCor3D_centerline
    
    if(parent not in removedNodeDict):
        return curDepth
    
    if(len(removedNodeDict[parent]) == 1):
        child = removedNodeDict[parent][0]
        parent_cor = pointsCor3D_centerline[parent]
        child_cor = pointsCor3D_centerline[child]
        graph_centerline.add_edge(parent, child , weight=distance.euclidean(parent_cor, child_cor))
        return addBackChildren(child, curDepth + 1)
    
    else:
        maxDepth = 0
        curChild = -1
        
        for child in removedNodeDict[parent]:
            parent_cor = pointsCor3D_centerline[parent]
            child_cor = pointsCor3D_centerline[child]
            graph_centerline.add_edge(parent, child , weight=distance.euclidean(parent_cor, child_cor))
            childDepth = addBackChildren(child, curDepth + 1)
            
            if(childDepth < maxDepth):
                deleteChild(parent, child)
            else:
                maxDepth = childDepth
                
                if(curChild != -1):
                    deleteChild(curChild)
                    
                curChild = child           
        return maxDepth
     

In [21]:
def pointCorToVector(pointCor):
    x = pointCor[0]
    y = pointCor[1]
    z = pointCor[2]
    return vector(x, y, z)

In [22]:
# Uncomment the next line if want to reload from file
filePath = "mri_label_2016/*.png"
pointData = ReadPointFromPNG(filePath)

# the temp.npy stores the colon data points from 2016 model
#pointData = np.load('./temp.npy')
(graph, pointsCor3D) = getMSTFromDataPoint(pointData, drawMST=False, sampleNumber=5000)

---------------
Begin reading points data from PNG files
There are 144 PNG files, now convert them to point coordinates in 3D
Done!
---------------
There are 818757 points in total. Now sampleling 5000 points from them
---------------
Done!
---------------
Begin creating a MST of the sampled points cloud
---------------
Begin calculating nearby points for each point
---------------
Nearby points calculation Done!
---------------
Begin construct graph
---------------
Graph construction Done!
---------------
Begin calculate MST
---------------
MST calculation Done!
---------------
MST creation Done!


In [23]:
displayPoints(pointsCor3D, 1.3)

In [24]:
# the code to move points toward the centerline 
points_centerline = []
# The total number of iterations
for iteration in range(2):
    points_centerline = []
    H_ini = 15
    H_delta = 5
    H_glo = 0
    trial_limit =10
    min_neighbors = 150
    max_neighbors = 750
    correlation_threshold = 0.2 + iteration*0.05
    weight_dict = {}
    distance_dict = {}

    # Set up a dirty dictionary to record the points 
    dirty_dict = {}
    for point in range(len(pointsCor3D)):
        dirty_dict[point] = 0
    results = []
    
    # We will move 750 points of all the points for each iteration
    for targetPoint in range(3000, 3750):
        
        cur_correlation = 0
        H_glo = H_ini
        trial = 0
        correlation_hist = []
        localPointsCor2D_hist = []
        planeInfo = 0
        localPointsCor2D = []
        curPlaneGuess = [1, 1, 1]
        #curScalar = np.zeros(10)
        #curALen = 0
        
        # if the correlation of the local points is not sufficient or the number of the local points is not sufficient
        # enlarge H_glo and find neighbors again  
        while(cur_correlation < correlation_threshold and len(localPointsCor2D) < max_neighbors \
               and trial < trial_limit):
            
            curPlaneGuess = [1, 1, 1]
            localPointsCor2D, planeInfo = get2DCorFrom3D(targetPoint)
            
            slope, intersept = calculateRegressionLine(localPointsCor2D)
            rotatedPointsCor = rotatePointsCor(localPointsCor2D, slope)
            cur_correlation = abs(np.corrcoef(rotatedPointsCor[:, 0],rotatedPointsCor[:, 1])[0][1])
            print(targetPoint, "trial",str(trial), "H =", H_glo, ":" , str(cur_correlation), \
                  "size:", len(localPointsCor2D))
            H_glo += H_delta
            trial += 1
            correlation_hist.append(cur_correlation)
            localPointsCor2D_hist.append(copy.deepcopy(localPointsCor2D))
            
        localPointsCor2D = localPointsCor2D_hist[correlation_hist.index(max(correlation_hist))]
        centerPoint2D = np.asarray(localPointsCor2D)[:1, :2]
        newCor = Moving_Least_Square(centerPoint2D[0], np.asarray(localPointsCor2D)[:, :2])
        newCor3D = get3DCorFrom2D(newCor, planeInfo)
        print(pointsCor3D[targetPoint], newCor3D)
        pointsCor3D[targetPoint] = list(newCor3D)
        dirty_dict[targetPoint] = 1
        results.append(max(correlation_hist))
        points_centerline.append(newCor3D)
        
    displayPoints(points_centerline, 0.5)    

3000 trial 0 H = 30 : 0.048493400837464666 size: 161
3000 trial 1 H = 40 : 0.2365369799640109 size: 298
[202 131 163] [203.04521722 131.73734488 165.82640477]
3001 trial 0 H = 45 : 0.6163208956552527 size: 177
[142 420  85] [138.98071386 416.96293219  85.46031492]
3002 trial 0 H = 40 : 0.2130906834447351 size: 171
[186 170 159] [181.85084678 165.94440094 157.36034278]
3003 trial 0 H = 45 : 0.022468635416163008 size: 268
3003 trial 1 H = 55 : 0.029293889096833482 size: 315
3003 trial 2 H = 65 : 0.06060981475812923 size: 354
3003 trial 3 H = 75 : 0.4196382730045302 size: 414
[105 324 172] [ 95.69970441 312.95451445 168.16181634]
3004 trial 0 H = 35 : 0.5011584372840296 size: 161
[132 243 177] [133.67632809 244.19566497 180.36919052]
3005 trial 0 H = 45 : 0.3421309982066587 size: 238
[111 403  87] [110.59733013 405.15090727  99.6766441 ]
3006 trial 0 H = 35 : 0.028698510365631015 size: 165
3006 trial 1 H = 45 : 0.24275679775650041 size: 313
[308 131 133] [305.08009563 128.59160355 139.479

3050 trial 0 H = 40 : 0.0732261509412293 size: 158
3050 trial 1 H = 50 : 0.0031736140428231764 size: 188
3050 trial 2 H = 60 : 0.28846136635034764 size: 457
[257  72 160] [263.66004633  78.37084365 153.36478612]
3051 trial 0 H = 40 : 0.34261862209619826 size: 188
[217  65 147] [225.59763162  72.96266907 151.9604975 ]
3052 trial 0 H = 40 : 0.10777956068846853 size: 323
3052 trial 1 H = 50 : 0.012989815062773727 size: 667
3052 trial 2 H = 60 : 0.05050825189000569 size: 859
[185 103 154] [184.90454516 103.13522113 163.46823913]
3053 trial 0 H = 50 : 0.6579583849812567 size: 173
[130 395 163] [131.0111747  399.67129193 151.59913349]
3054 trial 0 H = 35 : 0.10933140847083789 size: 160
3054 trial 1 H = 45 : 0.056615635770911645 size: 283
3054 trial 2 H = 55 : 0.036832271700128545 size: 391
3054 trial 3 H = 65 : 0.004472620180076665 size: 508
3054 trial 4 H = 75 : 0.013508368226649574 size: 631
3054 trial 5 H = 85 : 0.010885258223928398 size: 1164
[157 145 175] [158.93868079 147.991669   170.

3103 trial 0 H = 35 : 0.04410398030979143 size: 163
3103 trial 1 H = 45 : 0.17973889328423745 size: 221
3103 trial 2 H = 55 : 0.575500338795675 size: 280
[105 304 180] [107.16218263 304.78893536 170.84044998]
3104 trial 0 H = 45 : 0.38495736594418856 size: 215
[147 391 115] [153.3624143  397.45124712 127.02919407]
3105 trial 0 H = 45 : 0.6473598953854915 size: 163
[219 432 141] [229.91639503 440.60559603 140.7695074 ]
3106 trial 0 H = 35 : 0.00219476750962823 size: 157
3106 trial 1 H = 45 : 0.039011311620206254 size: 228
3106 trial 2 H = 55 : 0.29413817208049986 size: 295
[ 90 331 157] [ 84.20657956 328.53094284 163.92369134]
3107 trial 0 H = 40 : 0.441697093417183 size: 154
[186 436  87] [176.63401777 428.86181261  91.00134339]
3108 trial 0 H = 45 : 0.5281827366106607 size: 163
[128 189 177] [132.30524989 193.71012449 182.75769125]
3109 trial 0 H = 40 : 0.024624377700629967 size: 160
3109 trial 1 H = 50 : 0.04598614501260502 size: 203
3109 trial 2 H = 60 : 0.009907535658799815 size: 3

3153 trial 2 H = 55 : 0.10112606170396654 size: 253
3153 trial 3 H = 65 : 0.43033796385398976 size: 343
[248 444 141] [246.62199442 443.13083526 143.20083533]
3154 trial 0 H = 35 : 0.07686574515302326 size: 159
3154 trial 1 H = 45 : 0.01599392317488192 size: 349
3154 trial 2 H = 55 : 0.009930690892407465 size: 489
3154 trial 3 H = 65 : 0.18283412067504543 size: 733
3154 trial 4 H = 75 : 0.10737715876555141 size: 939
[204  75 147] [212.83309349  91.33370018 158.75406078]
3155 trial 0 H = 45 : 0.4529301767194724 size: 221
[178 122 165] [181.87396134 123.55178125 173.49361326]
3156 trial 0 H = 35 : 0.08119683598374637 size: 156
3156 trial 1 H = 45 : 0.04570627843033488 size: 269
3156 trial 2 H = 55 : 0.04124344874512424 size: 337
3156 trial 3 H = 65 : 0.09066458566612552 size: 557
3156 trial 4 H = 75 : 0.09985597090763475 size: 647
3156 trial 5 H = 85 : 0.11384020678071338 size: 701
3156 trial 6 H = 95 : 0.08555894736265497 size: 844
[305 103 159] [301.98117583  99.8464303  146.69036263]


3198 trial 2 H = 60 : 0.15052196506716453 size: 789
[229  85 166] [226.89042182  92.99443452 160.34409647]
3199 trial 0 H = 40 : 0.2396046732361943 size: 164
[ 89 349 157] [ 83.00771699 344.15729896 159.87306751]
3200 trial 0 H = 40 : 0.1601543049487285 size: 159
3200 trial 1 H = 50 : 0.20693680551308116 size: 216
[ 90 398 123] [ 99.10100262 401.64521302 109.01560197]
3201 trial 0 H = 40 : 0.16752742932047573 size: 168
3201 trial 1 H = 50 : 0.1936266192741327 size: 336
3201 trial 2 H = 60 : 0.03671411497622818 size: 639
3201 trial 3 H = 70 : 0.007752986574370213 size: 855
[181  86 181] [187.06231905  91.77949626 164.30806294]
3202 trial 0 H = 50 : 0.6675496026533927 size: 153
[329 390 157] [325.9821803  386.99863683 148.28484426]
3203 trial 0 H = 50 : 0.09067665271657041 size: 215
3203 trial 1 H = 60 : 0.2560489985998826 size: 249
[ 64 320 159] [ 76.96547769 334.83529151 160.37007682]
3204 trial 0 H = 35 : 0.006566110234095337 size: 205
3204 trial 1 H = 45 : 0.22355760126199087 size: 3

3248 trial 1 H = 60 : 0.252686085818787 size: 335
[147 384 144] [152.45980427 397.38311066 130.89565834]
3249 trial 0 H = 30 : 0.12245570788713458 size: 155
3249 trial 1 H = 40 : 0.3642217872205862 size: 336
[216 118 166] [213.65922763 115.66279685 165.60208211]
3250 trial 0 H = 40 : 0.10756619362473138 size: 269
3250 trial 1 H = 50 : 0.07829531669152116 size: 427
3250 trial 2 H = 60 : 0.45339300525642373 size: 585
[255 102 163] [249.38467316  96.01598095 152.11951382]
3251 trial 0 H = 40 : 0.12660403738258855 size: 167
3251 trial 1 H = 50 : 0.04795280647744322 size: 303
3251 trial 2 H = 60 : 0.07109184468868347 size: 380
3251 trial 3 H = 70 : 0.46861185544370165 size: 469
[375 321 165] [380.51105092 326.6584567  162.67652432]
3252 trial 0 H = 40 : 0.10176440478199134 size: 210
3252 trial 1 H = 50 : 0.024248499516941222 size: 353
3252 trial 2 H = 60 : 0.15516582320007186 size: 476
3252 trial 3 H = 70 : 0.24129569461795372 size: 689
[209  64 154] [227.022154    83.78572478 156.3426627 ]

3289 trial 4 H = 75 : 0.017277090198996994 size: 463
3289 trial 5 H = 85 : 0.2324527950039359 size: 510
[369 354 162] [364.37611814 350.40689041 162.3940648 ]
3290 trial 0 H = 35 : 0.21706861520685405 size: 183
[205  71 169] [208.35357074  76.7751322  163.14244579]
3291 trial 0 H = 50 : 0.06420663623490254 size: 161
3291 trial 1 H = 60 : 0.33906083932780884 size: 396
[276  70 147] [290.52061147  83.35268382 149.21379925]
3292 trial 0 H = 50 : 0.7458211832497355 size: 172
[329 362 154] [333.32580814 366.03310563 147.20338398]
3293 trial 0 H = 40 : 0.10600018210178389 size: 187
3293 trial 1 H = 50 : 0.442017387190752 size: 241
[117 310 171] [110.93937566 303.8651727  171.07821307]
3294 trial 0 H = 45 : 0.11514029250999162 size: 285
3294 trial 1 H = 55 : 0.04718588275843472 size: 359
3294 trial 2 H = 65 : 0.16874948885677066 size: 461
3294 trial 3 H = 75 : 0.09886215477788722 size: 493
3294 trial 4 H = 85 : 0.25963624644045774 size: 519
[352 355 148] [353.39505111 359.72911694 158.3032347

3339 trial 1 H = 55 : 0.03305506428525199 size: 247
3339 trial 2 H = 65 : 0.4979224921079096 size: 579
[266  73 166] [276.40891344  83.17722605 151.47302325]
3340 trial 0 H = 35 : 0.11924150393880091 size: 154
3340 trial 1 H = 45 : 0.0500296122620863 size: 279
3340 trial 2 H = 55 : 0.208489075866842 size: 547
[267 107 139] [268.4830073  108.72460354 148.81061142]
3341 trial 0 H = 45 : 0.6190994664085505 size: 162
[303 430 160] [296.97536205 424.8085512  153.48440103]
3342 trial 0 H = 45 : 0.5781473185276013 size: 169
[164 402  85] [163.85961545 402.05376635  86.61197281]
3343 trial 0 H = 45 : 0.015816897555926447 size: 231
3343 trial 1 H = 55 : 0.010747005396447523 size: 382
3343 trial 2 H = 65 : 0.0027104929316974034 size: 714
3343 trial 3 H = 75 : 0.01227928646422556 size: 933
[165 100 150] [172.3610545  106.80449572 165.55550459]
3344 trial 0 H = 50 : 0.4503098610997168 size: 199
[211 444  93] [203.17215498 435.30585708 111.89281128]
3345 trial 0 H = 90 : 0.23717488607921913 size: 3

[160 255 181] [157.57674133 252.45034047 176.91168884]
3388 trial 0 H = 45 : 0.4718886694840901 size: 190
[122 180 184] [124.13356545 181.50873601 180.8539861 ]
3389 trial 0 H = 35 : 0.30244054869289594 size: 160
[285 117 135] [284.62870109 117.39407143 144.35463572]
3390 trial 0 H = 30 : 0.03450221128109477 size: 157
3390 trial 1 H = 40 : 0.06376176178559766 size: 239
3390 trial 2 H = 50 : 0.09483544533073598 size: 284
3390 trial 3 H = 60 : 0.13082522822648668 size: 395
3390 trial 4 H = 70 : 0.1506687646217548 size: 487
3390 trial 5 H = 80 : 0.0525955891253879 size: 549
3390 trial 6 H = 90 : 0.12449645878114954 size: 616
3390 trial 7 H = 100 : 0.24156685002416708 size: 676
[156 265 178] [145.6013749  254.57863839 177.12422199]
3391 trial 0 H = 60 : 0.397172093359596 size: 172
[164 119 184] [170.88419142 127.40290864 177.61899653]
3392 trial 0 H = 50 : 0.707915261058935 size: 187
[117 385 156] [123.57351429 392.35520218 151.49498004]
3393 trial 0 H = 40 : 0.02548423881129314 size: 191


3440 trial 2 H = 65 : 0.1945552317249021 size: 347
3440 trial 3 H = 75 : 0.23754998520143247 size: 389
[103 385 114] [120.49124763 402.37636199 104.82210923]
3441 trial 0 H = 40 : 0.0036902060741665524 size: 165
3441 trial 1 H = 50 : 0.03209113756711505 size: 228
3441 trial 2 H = 60 : 0.19715653855735596 size: 329
3441 trial 3 H = 70 : 0.45906781803789215 size: 413
[146 289 162] [140.02324228 283.25467593 172.28239223]
3442 trial 0 H = 50 : 0.7044791813131973 size: 176
[118 398 166] [113.77157055 396.52024117 153.70465284]
3443 trial 0 H = 50 : 0.09737925047349522 size: 306
3443 trial 1 H = 60 : 0.3430585268028014 size: 382
[114 193 175] [120.4065359  200.42171629 180.34571387]
3444 trial 0 H = 50 : 0.32794193713314823 size: 160
[401 299 156] [392.64632846 290.67586845 156.88261706]
3445 trial 0 H = 50 : 0.3553593605300647 size: 197
[390 352 154] [379.53093268 344.2042279  167.25453603]
3446 trial 0 H = 80 : 0.41746945775467786 size: 152
[ 75 187 169] [ 94.19294325 207.23172138 177.056

[263 175 121] [259.46497977 173.00058577 128.22824094]
3485 trial 0 H = 40 : 0.2688776592558278 size: 161
[264 430 163] [269.77966245 433.22730473 153.03035411]
3486 trial 0 H = 50 : 0.011921298946384202 size: 174
3486 trial 1 H = 60 : 0.04151281056464035 size: 207
3486 trial 2 H = 70 : 0.01832150419471121 size: 349
3486 trial 3 H = 80 : 0.13317569227666665 size: 440
3486 trial 4 H = 90 : 0.09900922642839262 size: 556
3486 trial 5 H = 100 : 0.031610267650148724 size: 676
3486 trial 6 H = 110 : 0.014240200936649452 size: 745
3486 trial 7 H = 120 : 0.04974642898677678 size: 764
[284 166 133] [283.83207458 164.20878986 132.22254941]
3487 trial 0 H = 50 : 0.3702275065587286 size: 157
[169 220 186] [153.22226336 204.91755497 185.73806674]
3488 trial 0 H = 50 : 0.4715754263180487 size: 152
[159 430  67] [152.95917359 425.5432785   81.54640848]
3489 trial 0 H = 50 : 0.707694163977028 size: 167
[333 362 136] [334.45642418 363.91613494 145.74890672]
3490 trial 0 H = 40 : 0.6408799126932598 size

3539 trial 1 H = 45 : 0.009075358153779163 size: 341
3539 trial 2 H = 55 : 0.005626339503829286 size: 477
3539 trial 3 H = 65 : 0.07225539887104358 size: 752
[189  73 162] [208.14539233  72.64825755 158.10523716]
3540 trial 0 H = 40 : 0.2820117496784744 size: 164
[110 421 100] [105.21157987 415.33782393 100.16470347]
3541 trial 0 H = 50 : 0.6037083167215045 size: 156
[ 65 374 150] [ 78.30261818 388.13388852 152.03459319]
3542 trial 0 H = 40 : 0.0001416146348289862 size: 178
3542 trial 1 H = 50 : 0.13176243402059884 size: 265
3542 trial 2 H = 60 : 0.24531511160731362 size: 332
[148 288 169] [141.8052178  281.72524259 172.63979909]
3543 trial 0 H = 70 : 0.5229740635563379 size: 158
[368 227 157] [381.26980744 240.42386143 153.45608579]
3544 trial 0 H = 45 : 0.25295572658484783 size: 157
[184 185 147] [176.44453404 176.09881362 154.54992536]
3545 trial 0 H = 50 : 0.1769778090069595 size: 168
3545 trial 1 H = 60 : 0.5374141258539052 size: 238
[ 64 342 153] [ 77.55242798 351.19296384 155.65

3586 trial 6 H = 95 : 0.3492971890740153 size: 516
[367 354 181] [365.92270084 348.69960392 163.68951123]
3587 trial 0 H = 45 : 0.45752184200176194 size: 162
[166 439  79] [155.99979404 429.4278238   85.42190771]
3588 trial 0 H = 45 : 0.05621233333313745 size: 161
3588 trial 1 H = 55 : 0.3640092682103318 size: 284
[143 413 117] [136.41803372 405.31176531 128.92355336]
3589 trial 0 H = 40 : 0.07707937288702828 size: 174
3589 trial 1 H = 50 : 0.06101694335278076 size: 254
3589 trial 2 H = 60 : 0.14706982779762445 size: 328
3589 trial 3 H = 70 : 0.2171022410500236 size: 422
[314 147 129] [298.77205278 132.68493881 138.63074095]
3590 trial 0 H = 40 : 0.2413797760207795 size: 207
[154 150 180] [152.71079454 150.33706168 171.25307395]
3591 trial 0 H = 40 : 0.12211228485029973 size: 154
3591 trial 1 H = 50 : 0.25165558402412336 size: 271
[125 237 192] [129.58968097 240.02613842 180.67332672]
3592 trial 0 H = 35 : 0.2920055222548457 size: 196
[284 115 147] [283.814662   114.80938637 146.995315

3640 trial 0 H = 55 : 0.3911390081862792 size: 159
[141 410 162] [128.4603711  402.80998987 152.4366248 ]
3641 trial 0 H = 45 : 0.15417256816998817 size: 175
3641 trial 1 H = 55 : 0.18370407996626356 size: 236
3641 trial 2 H = 65 : 0.050291207217294194 size: 309
3641 trial 3 H = 75 : 0.07812440769347388 size: 378
3641 trial 4 H = 85 : 0.0022743413497581994 size: 587
3641 trial 5 H = 95 : 0.0382337097330478 size: 1128
[188 169 145] [202.96722504 179.83837359 159.41461311]
3642 trial 0 H = 45 : 0.3805756532328326 size: 167
[184 415  76] [185.77842532 416.82141347  88.53314504]
3643 trial 0 H = 50 : 0.029204149878874822 size: 166
3643 trial 1 H = 60 : 0.039306258430863585 size: 206
3643 trial 2 H = 70 : 0.004563264519334655 size: 324
3643 trial 3 H = 80 : 0.11866565836464942 size: 417
3643 trial 4 H = 90 : 0.18156940023445334 size: 476
3643 trial 5 H = 100 : 0.014676054773329155 size: 643
3643 trial 6 H = 110 : 0.033629611390804365 size: 712
3643 trial 7 H = 120 : 0.024812370454321504 siz

3679 trial 4 H = 75 : 0.035067970853443965 size: 458
3679 trial 5 H = 85 : 0.2112641488976693 size: 503
[363 351 180] [365.43786603 348.96286312 163.70567866]
3680 trial 0 H = 35 : 0.06681153289291228 size: 165
3680 trial 1 H = 45 : 0.12061575490907135 size: 259
3680 trial 2 H = 55 : 0.41638566302946606 size: 324
[152 276 180] [149.14018289 272.62670371 173.70671712]
3681 trial 0 H = 40 : 0.498937518722061 size: 164
[194 451 112] [193.03598749 450.78864231 114.49022799]
3682 trial 0 H = 40 : 0.1572526497710135 size: 185
3682 trial 1 H = 50 : 0.18768448203476737 size: 610
3682 trial 2 H = 60 : 0.05383804795166747 size: 843
[222  89 163] [220.91844263  88.51131376 160.3531328 ]
3683 trial 0 H = 40 : 0.4041430183618321 size: 208
[ 97 414  99] [ 92.55207039 409.72297247 102.44740125]
3684 trial 0 H = 40 : 0.2015395252946589 size: 189
[221 120 180] [216.27655459 114.92066251 168.32038955]
3685 trial 0 H = 45 : 0.19497567665247637 size: 150
3685 trial 1 H = 55 : 0.064615747660908 size: 325
3

3733 trial 0 H = 50 : 0.7168553766098366 size: 163
[117 408 160] [106.19214771 398.54538061 154.30783438]
3734 trial 0 H = 40 : 0.15201275592397698 size: 205
3734 trial 1 H = 50 : 0.10092898117736372 size: 287
3734 trial 2 H = 60 : 0.5238784073673467 size: 628
[271  85 142] [275.28577569  88.92627771 149.16413655]
3735 trial 0 H = 50 : 0.6369988760858512 size: 186
[382 303 159] [382.21043818 302.61424383 160.97941795]
3736 trial 0 H = 50 : 0.3533648531147792 size: 294
[120 404  85] [117.63655445 407.36520209  98.91242081]
3737 trial 0 H = 35 : 0.14621781800688335 size: 172
3737 trial 1 H = 45 : 0.05347478920590563 size: 300
3737 trial 2 H = 55 : 0.1339524445776631 size: 454
3737 trial 3 H = 65 : 0.07680039577501166 size: 672
3737 trial 4 H = 75 : 0.03611087731893151 size: 916
[199  68 168] [206.95701226  75.15836088 158.82872204]
3738 trial 0 H = 60 : 0.03547924911937871 size: 398
3738 trial 1 H = 70 : 0.04932925969874936 size: 441
3738 trial 2 H = 80 : 0.16215173727060828 size: 484
37

3033 trial 2 H = 55 : 0.2865350966910257 size: 561
[232  71 152] [241.56027382  80.86158095 155.80236728]
3034 trial 0 H = 50 : 0.42122592571068257 size: 160
[171 131 177] [170.26042028 130.18143649 177.07987971]
3035 trial 0 H = 40 : 0.23371742365794468 size: 205
3035 trial 1 H = 50 : 0.09756060448423926 size: 342
3035 trial 2 H = 60 : 0.007361078608588621 size: 501
3035 trial 3 H = 70 : 0.006120067728281965 size: 582
3035 trial 4 H = 80 : 0.021096339196945996 size: 706
3035 trial 5 H = 90 : 0.11836395500173098 size: 861
[148 160 171] [151.48125065 163.06822572 168.56543088]
3036 trial 0 H = 40 : 0.6685996009356995 size: 164
[297 423 152] [297.64170805 423.57100956 152.69332675]
3037 trial 0 H = 40 : 0.17072955479279364 size: 299
3037 trial 1 H = 50 : 0.11043833783142247 size: 344
3037 trial 2 H = 60 : 0.014618292574848271 size: 421
3037 trial 3 H = 70 : 0.022722572584167485 size: 448
3037 trial 4 H = 80 : 0.18352042889495518 size: 476
3037 trial 5 H = 90 : 0.7069026378833895 size: 57

3075 trial 1 H = 45 : 0.24355388621982005 size: 302
3075 trial 2 H = 55 : 0.20572357033725092 size: 661
3075 trial 3 H = 65 : 0.17374926551252898 size: 821
[231  81 156] [232.66926075  83.96915931 157.33229344]
3076 trial 0 H = 35 : 0.17141886431175962 size: 184
3076 trial 1 H = 45 : 0.2151328440159043 size: 298
3076 trial 2 H = 55 : 0.39491953378747646 size: 438
[311 121 143] [303.22784046 113.28102154 142.76224694]
3077 trial 0 H = 35 : 0.04606302418505244 size: 176
3077 trial 1 H = 45 : 0.28741434747925343 size: 311
[200 141 164] [196.43277579 137.90712625 166.68505547]
3078 trial 0 H = 35 : 0.5265093743605418 size: 159
[184  93 168] [183.45645755  92.51258761 167.36129471]
3079 trial 0 H = 40 : 0.024619662755824452 size: 184
3079 trial 1 H = 50 : 0.05364220586635295 size: 700
3079 trial 2 H = 60 : 0.08869874309729608 size: 924
[187 118 164] [187.00567126 117.88456608 165.8362744 ]
3080 trial 0 H = 35 : 0.31311961091747714 size: 157
[138 240 182] [136.87715296 239.85521698 180.98323

3123 trial 3 H = 70 : 0.061329319759882935 size: 541
3123 trial 4 H = 80 : 0.09623318464710826 size: 614
3123 trial 5 H = 90 : 0.24831840029505947 size: 669
3123 trial 6 H = 100 : 0.11470322153204557 size: 768
[142 263 176] [142.59515609 263.51434876 175.74701272]
3124 trial 0 H = 40 : 0.2905993037072628 size: 219
[150 400 132] [150.70392062 401.37812628 129.00582502]
3125 trial 0 H = 45 : 0.23261474560197948 size: 156
3125 trial 1 H = 55 : 0.2006374592493575 size: 203
3125 trial 2 H = 65 : 0.4100730147308836 size: 288
[109 172 175] [119.74900406 182.15439009 178.78889989]
3126 trial 0 H = 35 : 0.47203299783690983 size: 152
[285 430 151] [284.94413393 429.59909797 153.10762182]
3127 trial 0 H = 35 : 0.024827023881328826 size: 173
3127 trial 1 H = 45 : 0.09227783630468003 size: 263
3127 trial 2 H = 55 : 0.3827045662889414 size: 460
[290  91 149] [290.12767374  91.11907854 149.16257015]
3128 trial 0 H = 35 : 0.33226148799615907 size: 151
[135 200 184] [134.9801289  199.99226244 184.09581

3170 trial 3 H = 75 : 0.07438761936911041 size: 358
3170 trial 4 H = 85 : 0.316555803046884 size: 425
[395 285 156] [389.72528591 279.52493547 156.73780107]
3171 trial 0 H = 30 : 0.039158590673624476 size: 193
3171 trial 1 H = 40 : 0.12360634805952644 size: 297
3171 trial 2 H = 50 : 0.15898957558529558 size: 497
3171 trial 3 H = 60 : 0.025956897948517764 size: 766
[198  83 160] [204.5657991   88.64606689 160.30946038]
3172 trial 0 H = 35 : 0.13564327178205215 size: 152
3172 trial 1 H = 45 : 0.11738127207544868 size: 198
3172 trial 2 H = 55 : 0.0816663496896082 size: 254
3172 trial 3 H = 65 : 0.02336850294424292 size: 339
3172 trial 4 H = 75 : 0.04711559408371993 size: 503
3172 trial 5 H = 85 : 8.268299456003488e-06 size: 640
3172 trial 6 H = 95 : 0.08247581402866339 size: 1196
[181 171 153] [193.60533387 183.8264016  162.44345442]
3173 trial 0 H = 35 : 0.22856211596053677 size: 182
3173 trial 1 H = 45 : 0.22997223718016555 size: 237
3173 trial 2 H = 55 : 0.29882343258261657 size: 290
[

3210 trial 8 H = 110 : 0.11488158878011248 size: 804
[150 260 176] [150.28740975 260.19683386 176.25120418]
3211 trial 0 H = 40 : 0.6652724296201719 size: 165
[296 423 152] [296.85381518 423.84253351 152.09198726]
3212 trial 0 H = 35 : 0.2588320791377315 size: 170
[253 109 151] [250.83243363 106.8780397  151.43537187]
3213 trial 0 H = 35 : 0.32133728330265376 size: 186
[154 401 126] [154.21504278 400.95731393 128.92232551]
3214 trial 0 H = 40 : 0.2376312492016128 size: 255
3214 trial 1 H = 50 : 0.26903266203303555 size: 309
[116 400 106] [118.46298377 401.94641359 103.64689078]
3215 trial 0 H = 35 : 0.29285970705529096 size: 204
[373 333 167] [374.11520888 334.17469059 168.80319193]
3216 trial 0 H = 40 : 0.10854013513479913 size: 185
3216 trial 1 H = 50 : 0.049798581570442826 size: 222
3216 trial 2 H = 60 : 0.08732514800140738 size: 305
3216 trial 3 H = 70 : 0.16818033966039841 size: 358
3216 trial 4 H = 80 : 0.08121736247370988 size: 442
3216 trial 5 H = 90 : 0.002490965824634064 size

3260 trial 0 H = 30 : 0.012766183926146769 size: 151
3260 trial 1 H = 40 : 0.12448435743879359 size: 212
3260 trial 2 H = 50 : 0.19208500890936742 size: 293
3260 trial 3 H = 60 : 0.30744184388439993 size: 322
[ 88 318 166] [ 89.11509411 319.29856652 166.33003382]
3261 trial 0 H = 45 : 0.6597098193050985 size: 154
[327 381 148] [327.20038754 381.1319217  147.45724476]
3262 trial 0 H = 55 : 0.32589023571225795 size: 183
[ 70 410 104] [ 69.99395462 410.1442587  104.69784348]
3263 trial 0 H = 40 : 0.10508144424677819 size: 214
3263 trial 1 H = 50 : 0.0740203218274517 size: 355
3263 trial 2 H = 60 : 0.22200503593867502 size: 504
3263 trial 3 H = 70 : 0.07929053574217707 size: 671
3263 trial 4 H = 80 : 0.06901790888832982 size: 728
3263 trial 5 H = 90 : 0.01859166468133683 size: 754
[282 135 139] [280.78246632 132.82253232 140.27415407]
3264 trial 0 H = 45 : 0.05524337758174957 size: 167
3264 trial 1 H = 55 : 0.32440593039943083 size: 394
[273  77 155] [282.86237169  86.62719889 151.2827167 

3305 trial 2 H = 55 : 0.2934490751447754 size: 326
[139 283 173] [138.91649942 282.89741313 172.74472691]
3306 trial 0 H = 40 : 0.2222442696186993 size: 174
3306 trial 1 H = 50 : 0.02074642206172631 size: 227
3306 trial 2 H = 60 : 0.10971384184108407 size: 296
3306 trial 3 H = 70 : 0.02306789387867373 size: 370
3306 trial 4 H = 80 : 0.03902203496094213 size: 556
3306 trial 5 H = 90 : 0.038327541889039446 size: 1116
[184 169 152] [199.13139655 184.50458807 160.17718119]
3307 trial 0 H = 40 : 0.28185109567271605 size: 158
[151 208 184] [147.20230783 204.70802826 185.33895094]
3308 trial 0 H = 30 : 0.00550002439108549 size: 170
3308 trial 1 H = 40 : 0.07506494466375029 size: 280
3308 trial 2 H = 50 : 0.09245874824639745 size: 380
3308 trial 3 H = 60 : 0.254398241977708 size: 554
[301 108 144] [296.49949941 103.5562137  145.35232097]
3309 trial 0 H = 40 : 0.173325190684792 size: 201
3309 trial 1 H = 50 : 0.003852357931831172 size: 316
3309 trial 2 H = 60 : 0.04179502678027927 size: 377
330

3358 trial 0 H = 40 : 0.07276800424116088 size: 163
3358 trial 1 H = 50 : 0.05470573418580867 size: 275
3358 trial 2 H = 60 : 0.007364790449960043 size: 669
3358 trial 3 H = 70 : 0.0030173491369134653 size: 1037
[167 115 164] [173.02679111 117.68371654 167.06670022]
3359 trial 0 H = 40 : 0.2032166853305351 size: 248
3359 trial 1 H = 50 : 0.18357635509106796 size: 419
3359 trial 2 H = 60 : 0.278874441933167 size: 490
[247 107 152] [241.0423829  101.02789873 150.95758315]
3360 trial 0 H = 35 : 0.038381718426640135 size: 157
3360 trial 1 H = 45 : 0.030633558820430663 size: 280
3360 trial 2 H = 55 : 0.4279090964909604 size: 562
[268  85 150] [270.24473351  87.13535118 150.82348658]
3361 trial 0 H = 40 : 0.20805907918114597 size: 223
3361 trial 1 H = 50 : 0.23092207642614468 size: 306
3361 trial 2 H = 60 : 0.15741275634230034 size: 374
3361 trial 3 H = 70 : 0.333912455243893 size: 417
[113 394 112] [120.92681103 403.4956039  104.83558568]
3362 trial 0 H = 35 : 0.03335917220077659 size: 202


3398 trial 3 H = 60 : 0.04036013896561157 size: 760
[201 134 167] [206.69453556 139.51551022 162.34329997]
3399 trial 0 H = 45 : 0.6365809330960949 size: 185
[160 407  85] [169.95061223 417.08574703  87.92588839]
3400 trial 0 H = 35 : 0.23410236422765127 size: 211
3400 trial 1 H = 45 : 0.2584192368728594 size: 304
[363 355 162] [362.68832758 354.98123287 162.70435929]
3401 trial 0 H = 30 : 0.06677786120525513 size: 189
3401 trial 1 H = 40 : 0.023796958552575975 size: 267
3401 trial 2 H = 50 : 0.04398222099108124 size: 307
3401 trial 3 H = 60 : 0.07120132228206524 size: 540
3401 trial 4 H = 70 : 0.08191730969004819 size: 668
3401 trial 5 H = 80 : 0.1534028356075622 size: 702
3401 trial 6 H = 90 : 0.1407776677764005 size: 855
[296  99 146] [298.59371099 102.2017019  145.47833771]
3402 trial 0 H = 35 : 0.07766072330413369 size: 221
3402 trial 1 H = 45 : 0.3153423677024844 size: 310
[146 250 179] [145.8808085  249.86600213 178.52485558]
3403 trial 0 H = 35 : 0.0008044642700340201 size: 156

3448 trial 3 H = 75 : 0.1777024912980598 size: 342
3448 trial 4 H = 85 : 0.019940028743356084 size: 659
3448 trial 5 H = 95 : 0.08375139753042309 size: 787
[184 184 159] [190.09115231 188.69523478 154.98398682]
3449 trial 0 H = 30 : 0.0969936870842917 size: 188
3449 trial 1 H = 40 : 6.464066134508477e-05 size: 283
3449 trial 2 H = 50 : 0.07979303060776684 size: 371
3449 trial 3 H = 60 : 0.028135492225071234 size: 542
3449 trial 4 H = 70 : 0.02888579356058482 size: 670
3449 trial 5 H = 80 : 0.14467424073674887 size: 702
3449 trial 6 H = 90 : 0.09220434977899734 size: 854
[297 104 145] [297.46708265 105.2095659  144.86681801]
3450 trial 0 H = 40 : 0.2801153308700253 size: 233
[158 247 177] [157.80124131 246.36325178 177.31027185]
3451 trial 0 H = 35 : 0.203028286219028 size: 201
3451 trial 1 H = 45 : 0.2819019347054681 size: 314
[359 355 159] [358.33918195 354.68378298 159.5743649 ]
3452 trial 0 H = 30 : 0.1236056353721039 size: 166
3452 trial 1 H = 40 : 0.30756899068633864 size: 361
[21

3489 trial 0 H = 50 : 0.7014135062226335 size: 170
[334 363 145] [333.71590444 362.81000484 146.25735829]
3490 trial 0 H = 40 : 0.5988238159069162 size: 161
[294 424 153] [294.91166056 424.94476411 152.28457383]
3491 trial 0 H = 45 : 0.2502073639207877 size: 153
[109 178 176] [111.78438347 181.22410202 177.64290404]
3492 trial 0 H = 40 : 0.5048172944216596 size: 170
[231 443 137] [231.91901806 444.05663207 138.19240263]
3493 trial 0 H = 40 : 0.18988361585496535 size: 253
3493 trial 1 H = 50 : 0.26244481751811477 size: 401
[238  96 151] [235.63971732  93.76878844 152.42965728]
3494 trial 0 H = 40 : 0.6049835979548611 size: 153
[314 407 150] [313.96532753 406.92834536 150.55392804]
3495 trial 0 H = 45 : 0.20019183745087066 size: 199
3495 trial 1 H = 55 : 0.08255364510935127 size: 398
3495 trial 2 H = 65 : 0.04099631491611337 size: 550
3495 trial 3 H = 75 : 0.02984077421092368 size: 679
3495 trial 4 H = 85 : 0.0538696659775071 size: 809
[157 175 167] [167.95006133 184.76744992 166.0642480

[141 281 172] [140.67864221 280.70189488 172.99368146]
3543 trial 0 H = 55 : 0.565178083041378 size: 160
[381 240 153] [383.28355192 242.10969488 153.35766154]
3544 trial 0 H = 40 : 0.0033151928292495013 size: 175
3544 trial 1 H = 50 : 0.03910098437160337 size: 222
3544 trial 2 H = 60 : 0.2047245310872584 size: 268
3544 trial 3 H = 70 : 0.058471262984116076 size: 458
3544 trial 4 H = 80 : 0.022439085844030905 size: 627
3544 trial 5 H = 90 : 0.014957281104509336 size: 757
[176 176 154] [180.97517163 177.14454882 159.1318983 ]
3545 trial 0 H = 40 : 0.4365402100697458 size: 154
[ 77 351 155] [ 78.24325971 352.68103096 156.05951161]
3546 trial 0 H = 40 : 0.09928776723877658 size: 219
3546 trial 1 H = 50 : 0.3119844143847919 size: 400
[272  86 150] [277.23741286  90.92005331 151.34583683]
3547 trial 0 H = 60 : 0.497586542005862 size: 160
[383 234 153] [385.39442128 236.39880076 152.69239459]
3548 trial 0 H = 40 : 0.5904993942016963 size: 172
[179 422  98] [181.2776796  423.50683145  97.1105

3589 trial 0 H = 40 : 0.13558860192176028 size: 288
3589 trial 1 H = 50 : 0.24421256022630225 size: 375
3589 trial 2 H = 60 : 0.29194577408062333 size: 480
[298 132 138] [293.65956737 127.84313232 140.68371684]
3590 trial 0 H = 35 : 0.2541697142534232 size: 173
[152 150 171] [152.57659365 150.5989993  170.85448796]
3591 trial 0 H = 35 : 0.3411928127474688 size: 153
[129 240 180] [129.67495267 240.79217709 180.23567013]
3592 trial 0 H = 35 : 0.1986444781019412 size: 199
3592 trial 1 H = 45 : 0.011332036931761599 size: 414
3592 trial 2 H = 55 : 0.05277733609342616 size: 552
3592 trial 3 H = 65 : 0.08727699093640244 size: 679
3592 trial 4 H = 75 : 0.011503978185940384 size: 745
3592 trial 5 H = 85 : 0.08963180801333909 size: 862
[283 114 146] [287.66467321 119.04621485 142.76803543]
3593 trial 0 H = 45 : 0.48160093464138604 size: 198
[152 202 185] [142.22970316 193.7919768  184.9727149 ]
3594 trial 0 H = 35 : 0.31006957089932713 size: 197
[377 345 166] [376.10348284 344.51951707 168.17477

3632 trial 0 H = 35 : 0.03195712249312999 size: 206
3632 trial 1 H = 45 : 0.027715690464080196 size: 627
3632 trial 2 H = 55 : 0.03201554052792348 size: 844
[195  99 162] [197.62803186 101.42889945 162.65960968]
3633 trial 0 H = 45 : 0.650647534003258 size: 162
[330 371 147] [330.79951709 371.78533973 147.20671161]
3634 trial 0 H = 35 : 0.14294102191980496 size: 160
3634 trial 1 H = 45 : 0.06625654354882353 size: 237
3634 trial 2 H = 55 : 0.015697053002432335 size: 282
3634 trial 3 H = 65 : 0.029552083723002855 size: 498
3634 trial 4 H = 75 : 0.032046190868053825 size: 635
3634 trial 5 H = 85 : 0.02207838091714046 size: 749
3634 trial 6 H = 95 : 0.12936019544561536 size: 1259
[168 170 164] [179.65802617 181.24341706 167.16130325]
3635 trial 0 H = 35 : 0.5786004687956645 size: 169
[184  96 164] [182.21989588  93.54865699 167.16525391]
3636 trial 0 H = 35 : 0.36160663140940735 size: 206
[221 122 161] [217.74459797 119.14888424 163.75985714]
3637 trial 0 H = 50 : 0.7153685679726028 size: 

3675 trial 1 H = 45 : 0.2982497779675968 size: 246
[ 98 311 168] [ 97.70859966 311.07934991 169.42618169]
3676 trial 0 H = 45 : 0.11781332433534618 size: 163
3676 trial 1 H = 55 : 0.19506271014978632 size: 320
3676 trial 2 H = 65 : 0.14263612748799123 size: 431
3676 trial 3 H = 75 : 0.05814429192720621 size: 593
3676 trial 4 H = 85 : 0.034397397698178005 size: 697
3676 trial 5 H = 95 : 0.022001917781514006 size: 751
[276 149 136] [276.76947642 147.61841894 136.72810892]
3677 trial 0 H = 40 : 0.2985011549425317 size: 201
[224  77 154] [223.87011592  76.97042037 153.38398706]
3678 trial 0 H = 40 : 0.14756902610932157 size: 154
3678 trial 1 H = 50 : 0.18355878720776736 size: 280
3678 trial 2 H = 60 : 0.11737825379834765 size: 384
3678 trial 3 H = 70 : 0.09831571662669072 size: 537
3678 trial 4 H = 80 : 0.013642628737697867 size: 739
3678 trial 5 H = 90 : 0.028314294479500825 size: 810
[127 173 173] [126.26886467 171.46892097 174.54603478]
3679 trial 0 H = 35 : 0.0588922517301617 size: 249

3726 trial 1 H = 45 : 0.2893926586079352 size: 407
[279 104 149] [277.91473779 102.93652196 149.00068698]
3727 trial 0 H = 35 : 0.10581307385597911 size: 245
3727 trial 1 H = 45 : 0.1921694956772486 size: 310
3727 trial 2 H = 55 : 0.057129253421021486 size: 405
3727 trial 3 H = 65 : 0.09397216233361481 size: 433
3727 trial 4 H = 75 : 0.001291949636933913 size: 464
3727 trial 5 H = 85 : 0.3651719324375506 size: 514
[364 350 161] [363.92745265 350.26882336 162.2639145 ]
3728 trial 0 H = 40 : 0.0014827028020146852 size: 184
3728 trial 1 H = 50 : 0.0038754916780710425 size: 610
3728 trial 2 H = 60 : 0.04237211657149338 size: 907
[178 115 165] [182.26356989 118.96482811 166.73986762]
3729 trial 0 H = 35 : 0.26183341287349116 size: 195
[195 122 163] [198.67839488 123.68771249 168.23099592]
3730 trial 0 H = 50 : 0.5073726213375894 size: 169
[105 202 178] [109.70861185 206.93491268 179.58074611]
3731 trial 0 H = 35 : 0.35332406145241346 size: 170
[187 120 172] [187.38857355 119.90420045 173.71

In [25]:
# Construct a MST only using the 750 points modified above
#points_centerline = np.load('archive_npyfile/demoCenterline.npy')
(graph_centerline, pointsCor3D_centerline) = getMSTFromDataPoint(points_centerline, drawMST=True, sampleNumber=750)  

# constantly delete the node that only has one edge, until there are only two nodes only having one edge left,
# both of them are the endpoints of one singal path representing the colon

toRemove = []
removeCount = 0
removedNodeDict = defaultdict(list)

print("MST has", len(pointsCor3D_centerline), "nodes. Now begin to trim the graph.")

while (True):
    toRemove = []
    for node in graph_centerline.nodes():
        if(len(graph_centerline.edges(node)) == 1):
            removedNodeDict[list(graph_centerline.edges(node))[0][1]].append(node)
            toRemove.append(node)
    if(len(toRemove) == 2):
        break
    for node in toRemove:
        graph_centerline.remove_node(node)
        removeCount += 1
        toRemove = []
        
        
endpoints = toRemove
print("Done! Trimed", removeCount, "nodes. Now MST has", len(graph_centerline.nodes), "nodes left.")

print("Now begin reconstruct endpoints")
# now add back the nodes that got deleted during the triming
addBackChildren(endpoints[0], 0)
addBackChildren(endpoints[1], 0)

print("Done! Now MST has", len(graph_centerline.nodes), "nodes left.")
# Displat the points on the centerline
'''
to_display = []
for node in graph_centerline.nodes:
    to_display.append(pointsCor3D_centerline[node])
displayPoints(to_display, 1.3)
'''
# check if there is more than 2 endpoints
new_endpoints = []
for node in graph_centerline.nodes:
    if(len(graph_centerline.edges(node)) == 1):
       new_endpoints.append(node)
if(len(new_endpoints) != 2):
    print("Fatal error: multiple endpoints detected!")

# check if there is more than 2 path
path = list(nx.all_simple_paths(graph_centerline, source=new_endpoints[0], target=new_endpoints[1]))
if(len(path) != 1):
    print("Fatal error: multiple path detected!")
    
pointsInorder = path[0]

---------------
There are 750 points in total. Now sampleling 750 points from them
---------------
Done!
---------------
Begin creating a MST of the sampled points cloud
---------------
Begin calculating nearby points for each point
---------------
Nearby points calculation Done!
---------------
Begin construct graph
---------------
Graph construction Done!
---------------
Begin calculate MST
---------------
MST calculation Done!
---------------
MST creation Done!
MST has 750 nodes. Now begin to trim the graph.
Done! Trimed 409 nodes. Now MST has 341 nodes left.
Now begin reconstruct endpoints
Done! Now MST has 377 nodes left.


C:\Users\lizif\Anaconda3\envs\MIP3D\lib\site-packages\networkx\drawing\nx_pylab.py:611: MatplotlibDeprecationWarning: isinstance(..., numbers.Number)
  if cb.is_numlike(alpha):


In [26]:
c = curve()
for pointIndex in pointsInorder:
    c.append(pointCorToVector(pointsCor3D_centerline[pointIndex]))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [28]:
toDisplay=[]
for node in graph_centerline.nodes():
    toDisplay.append(pointsCor3D_centerline[node])
displayPoints(toDisplay, 1.3)