In [1]:
from trainingLib import *

W1004 15:20:53.720939 24036 deprecation_wrapper.py:119] From C:\Users\Zifeng Li\Desktop\HelmsleyDocker\Helmsley3DMIP\_Scripts\Utilities\networkTrain\test_model.py:4: The name tf.keras.layers.CuDNNGRU is deprecated. Please use tf.compat.v1.keras.layers.CuDNNGRU instead.

W1004 15:20:53.722944 24036 deprecation_wrapper.py:119] From C:\Users\Zifeng Li\Desktop\HelmsleyDocker\Helmsley3DMIP\_Scripts\Utilities\networkTrain\test_model.py:4: The name tf.keras.layers.CuDNNLSTM is deprecated. Please use tf.compat.v1.keras.layers.CuDNNLSTM instead.



In [2]:
# Run this block to prepare all the training data
pruneSystem()

Deleting old training files and temp files.
Deleting directory ./sampledDataset failed
Deleting directory ./sampledLabel failed


In [3]:
dicomPaths, maskPaths = getDataPaths()

In [4]:
createTrainingData(dicomPaths, maskPaths, 1)

Creating training PNG files.
Successfully created the directory ./tmp 
Successfully created the directory ./tmp/trainingImage 
Successfully created the directory ./tmp/trainingMask 
Processing data series 0
Processing data series 1
Processing data series 2
Error. Shape difference. (512, 512) (256, 256, 3)
Error. Shape difference. (512, 512) (256, 256, 3)
Error. Shape difference. (512, 512) (256, 256, 3)
Error. Shape difference. (512, 512) (256, 256, 3)
Error. Shape difference. (512, 512) (256, 256, 3)
Error. Shape difference. (512, 512) (256, 256, 3)
Error. Shape difference. (512, 512) (256, 256, 3)
Error. Shape difference. (512, 512) (256, 256, 3)
Error. Shape difference. (512, 512) (256, 256, 3)
Error. Shape difference. (512, 512) (256, 256, 3)
Error. Shape difference. (512, 512) (256, 256, 3)
Error. Shape difference. (512, 512) (256, 256, 3)
Error. Shape difference. (512, 512) (256, 256, 3)
Error. Shape difference. (512, 512) (256, 256, 3)
Error. Shape difference. (512, 512) (256, 2

Error. Shape difference. (512, 512) (512, 512, 3)
Error. Shape difference. (512, 512) (512, 512, 3)
Error. Shape difference. (512, 512) (512, 512, 3)
Error. Shape difference. (512, 512) (512, 512, 3)
Error. Shape difference. (512, 512) (512, 512, 3)
Error. Shape difference. (512, 512) (512, 512, 3)
Error. Shape difference. (512, 512) (512, 512, 3)
Error. Shape difference. (512, 512) (512, 512, 3)
Error. Shape difference. (512, 512) (512, 512, 3)
Error. Shape difference. (512, 512) (512, 512, 3)
Error. Shape difference. (512, 512) (512, 512, 3)
Error. Shape difference. (512, 512) (512, 512, 3)
Error. Shape difference. (512, 512) (512, 512, 3)
Error. Shape difference. (512, 512) (512, 512, 3)
Error. Shape difference. (512, 512) (512, 512, 3)
Error. Shape difference. (512, 512) (512, 512, 3)
Error. Shape difference. (512, 512) (512, 512, 3)
Error. Shape difference. (512, 512) (512, 512, 3)
Error. Shape difference. (512, 512) (512, 512, 3)
Error. Shape difference. (512, 512) (512, 512, 3)


In [2]:
trainUnet(COLOR_DICT, multiLabel=True)

W1004 15:20:55.333108 24036 deprecation.py:506] From C:\Users\Zifeng Li\Anaconda3\envs\Helmsley3DMIP\lib\site-packages\tensorflow\python\ops\init_ops.py:1288: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 6937002287729347528
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 6667611669
locality {
  bus_id: 1
  links {
  }
}
incarnation: 8854844655693537910
physical_device_desc: "device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1"
]


W1004 15:20:56.454077 24036 deprecation.py:323] From C:\Users\Zifeng Li\Anaconda3\envs\Helmsley3DMIP\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 64, 64, 3)]  0                                            
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 64, 64, 64)   1792        input_1[0][0]                    
__________________________________________________________________________________________________
leaky_re_lu (LeakyReLU)         (None, 64, 64, 64)   0           conv2d[0][0]                     
__________________________________________________________________________________________________
batch_normalization (BatchNorma (None, 64, 64, 64)   256         leaky_re_lu[0][0]                
______________________________________________________________________________________________

Found 8192 images belonging to 1 classes.
Found 8192 images belonging to 1 classes.
Epoch 1/5
4096/4096 [==============================] - 396s 97ms/step - loss: 2.5665 - acc: 0.9200
Epoch 2/5
4096/4096 [==============================] - 389s 95ms/step - loss: 0.2154 - acc: 0.9693
Epoch 3/5
4096/4096 [==============================] - 388s 95ms/step - loss: 0.1165 - acc: 0.97155s  - ETA: 2s - loss: 0.1166 - acc: 0. - ETA: 2s -
Epoch 4/5
4096/4096 [==============================] - 387s 95ms/step - loss: 0.0970 - acc: 0.97214s - loss: 0. - ETA: 2s - loss - ETA: 0s - loss: 0.0970 - acc: 
Epoch 5/5
4096/4096 [==============================] - 389s 95ms/step - loss: 0.0921 - acc: 0.9726


In [6]:
createTestingData(1, "pa3_lava_post3")

Creating testing PNG files.
Successfully created the directory ./tmp/testingImage 

 Done! Converted 112 images.


In [7]:
testUnet(COLOR_DICT, "./model_archive/segmentation_10_01_13_47.hdf5", multiLabel=True)

W1004 13:20:20.801159 32784 deprecation.py:506] From C:\Users\Zifeng Li\Anaconda3\envs\Helmsley3DMIP\lib\site-packages\tensorflow\python\ops\init_ops.py:1288: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 8345351563898921012
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 6667611669
locality {
  bus_id: 1
  links {
  }
}
incarnation: 16296387430642209611
physical_device_desc: "device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1"
]


W1004 13:20:22.026159 32784 deprecation.py:323] From C:\Users\Zifeng Li\Anaconda3\envs\Helmsley3DMIP\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 256, 256, 3) 0                                            
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 256, 256, 64) 1792        input_1[0][0]                    
__________________________________________________________________________________________________
leaky_re_lu (LeakyReLU)         (None, 256, 256, 64) 0           conv2d[0][0]                     
__________________________________________________________________________________________________
batch_normalization (BatchNorma (None, 256, 256, 64) 256         leaky_re_lu[0][0]                
______________________________________________________________________________________________

112/112 [==============================] - 5s 47ms/step
Successfully created the directory ./predicted_segmnetation_10_04_13_20 


C:\Users\Zifeng Li\Anaconda3\envs\Helmsley3DMIP\lib\site-packages\skimage\io\_io.py:141: UserWarning: ./predicted_segmnetation_10_04_13_20\0.png is a low contrast image
  warn('%s is a low contrast image' % fname)
W1004 13:20:28.859039 32784 util.py:64] Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
C:\Users\Zifeng Li\Anaconda3\envs\Helmsley3DMIP\lib\site-packages\skimage\io\_io.py:141: UserWarning: ./predicted_segmnetation_10_04_13_20\1.png is a low contrast image
  warn('%s is a low contrast image' % fname)
W1004 13:20:28.918030 32784 util.py:64] Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
C:\Users\Zifeng Li\Anaconda3\envs\Helmsley3DMIP\lib\site-packages\skimage\io\_io.py:141: UserWarning: ./predicted_segmnetation_10_04_13_20\2.png is a low contrast image
  warn('%s is a low contrast image' % fname)
W1004 13:20:28.977041 32784 util.py:64] 

W1004 13:20:31.157001 32784 util.py:64] Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W1004 13:20:31.224031 32784 util.py:64] Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W1004 13:20:31.290003 32784 util.py:64] Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W1004 13:20:31.357038 32784 util.py:64] Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W1004 13:20:31.423001 32784 util.py:64] Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W1004 13:20:31.491030 32784 util.py:64] Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W1004 13:20:31.557034 32784 util.py:64] Lossy 

W1004 13:20:33.827027 32784 util.py:64] Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
C:\Users\Zifeng Li\Anaconda3\envs\Helmsley3DMIP\lib\site-packages\skimage\io\_io.py:141: UserWarning: ./predicted_segmnetation_10_04_13_20\78.png is a low contrast image
  warn('%s is a low contrast image' % fname)
W1004 13:20:33.889000 32784 util.py:64] Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
C:\Users\Zifeng Li\Anaconda3\envs\Helmsley3DMIP\lib\site-packages\skimage\io\_io.py:141: UserWarning: ./predicted_segmnetation_10_04_13_20\79.png is a low contrast image
  warn('%s is a low contrast image' % fname)
W1004 13:20:33.949031 32784 util.py:64] Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
C:\Users\Zifeng Li\Anaconda3\envs\Helmsley3DMIP\lib\site-packages\skimage\io\_io.py:141: User

C:\Users\Zifeng Li\Anaconda3\envs\Helmsley3DMIP\lib\site-packages\skimage\io\_io.py:141: UserWarning: ./predicted_segmnetation_10_04_13_20\100.png is a low contrast image
  warn('%s is a low contrast image' % fname)
W1004 13:20:35.232010 32784 util.py:64] Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
C:\Users\Zifeng Li\Anaconda3\envs\Helmsley3DMIP\lib\site-packages\skimage\io\_io.py:141: UserWarning: ./predicted_segmnetation_10_04_13_20\101.png is a low contrast image
  warn('%s is a low contrast image' % fname)
W1004 13:20:35.292002 32784 util.py:64] Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
C:\Users\Zifeng Li\Anaconda3\envs\Helmsley3DMIP\lib\site-packages\skimage\io\_io.py:141: UserWarning: ./predicted_segmnetation_10_04_13_20\102.png is a low contrast image
  warn('%s is a low contrast image' % fname)
W1004 13:20:35.352035 32784 util.p

In [39]:
image = np.mgrid[0:8, 0:8][1]
print(image)
shape = image.shape
tileN = 4
tileS = int(shape[0]/tileN)

for i in range(tileN):
    for j in range(tileN):
        mri_tile = image[i*tileS:(i+1)*tileS, j*tileS:(j+1)*tileS,]
        print(mri_tile)
        #mask_tile = mask[i*tileS:(i+1)*tileS, j*tileS:(j+1)*tileS,]

[[0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]]
[[0 1]
 [0 1]]
[[2 3]
 [2 3]]
[[4 5]
 [4 5]]
[[6 7]
 [6 7]]
[[0 1]
 [0 1]]
[[2 3]
 [2 3]]
[[4 5]
 [4 5]]
[[6 7]
 [6 7]]
[[0 1]
 [0 1]]
[[2 3]
 [2 3]]
[[4 5]
 [4 5]]
[[6 7]
 [6 7]]
[[0 1]
 [0 1]]
[[2 3]
 [2 3]]
[[4 5]
 [4 5]]
[[6 7]
 [6 7]]
